import type { MuscleId, MuscleInfo } from './types';

export const muscleMetadata: Record<MuscleId, MuscleInfo> = {
  chest: {
    id: 'chest',
    label: 'Chest',
    shortLabel: 'Chest',
    category: 'Upper Body',
    description: 'Used in pressing movements and shoulder flexion.',
  },
  front_delts: {
    id: 'front_delts',
    label: 'Front Delts',
    shortLabel: 'Front Delts',
    category: 'Shoulders',
    description: 'Assist with shoulder flexion and pressing movements.',
  },
  side_delts: {
    id: 'side_delts',
    label: 'Side Delts',
    shortLabel: 'Side Delts',
    category: 'Shoulders',
    description: 'Assist with shoulder abduction and shoulder stability.',
  },
  rear_delts: {
    id: 'rear_delts',
    label: 'Rear Delts',
    shortLabel: 'Rear Delts',
    category: 'Shoulders',
    description: 'Assist with pulling movements and shoulder extension.',
  },
  traps: {
    id: 'traps',
    label: 'Traps',
    shortLabel: 'Traps',
    category: 'Back',
    description: 'Support posture, shoulder elevation, and upper-back stability.',
  },
  lats: {
    id: 'lats',
    label: 'Lats',
    shortLabel: 'Lats',
    category: 'Back',
    description: 'Assist with pulling, shoulder extension, and back strength.',
  },
  biceps: {
    id: 'biceps',
    label: 'Biceps',
    shortLabel: 'Biceps',
    category: 'Arms',
    description: 'Flex the elbow and assist with pulling movements.',
  },
  triceps: {
    id: 'triceps',
    label: 'Triceps',
    shortLabel: 'Triceps',
    category: 'Arms',
    description: 'Extend the elbow and assist with pressing movements.',
  },
  forearms: {
    id: 'forearms',
    label: 'Forearms',
    shortLabel: 'Forearms',
    category: 'Arms',
    description: 'Support grip, wrist control, and load stability.',
  },
  abs: {
    id: 'abs',
    label: 'Abs',
    shortLabel: 'Abs',
    category: 'Core',
    description: 'Brace the torso and help maintain trunk control.',
  },
  obliques: {
    id: 'obliques',
    label: 'Obliques',
    shortLabel: 'Obliques',
    category: 'Core',
    description: 'Assist with rotation, anti-rotation, and lateral trunk stability.',
  },
  lower_back: {
    id: 'lower_back',
    label: 'Lower Back',
    shortLabel: 'Lower Back',
    category: 'Back',
    description: 'Supports spinal extension and torso stability.',
  },
  glutes: {
    id: 'glutes',
    label: 'Glutes',
    shortLabel: 'Glutes',
    category: 'Lower Body',
    description: 'Drive hip extension and lower-body power.',
  },
  quadriceps: {
    id: 'quadriceps',
    label: 'Quadriceps',
    shortLabel: 'Quads',
    category: 'Lower Body',
    description: 'Extend the knee and are heavily used in squatting movements.',
  },
  hamstrings: {
    id: 'hamstrings',
    label: 'Hamstrings',
    shortLabel: 'Hamstrings',
    category: 'Lower Body',
    description: 'Assist hip extension and knee flexion.',
  },
  calves: {
    id: 'calves',
    label: 'Calves',
    shortLabel: 'Calves',
    category: 'Lower Body',
    description: 'Assist ankle extension and lower-leg stability.',
  },
  adductors: {
    id: 'adductors',
    label: 'Adductors',
    shortLabel: 'Adductors',
    category: 'Lower Body',
    description: 'Assist hip adduction and stabilize the lower body.',
  },
};
